version: '3.8'

services:
  db:
    image: postgres:16
    container_name: server-postgres16
    restart: always
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: prueba
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_server

volumes:
  postgres_data:

networks:
  fastapi_net:
    driver: bridge