version: '3.8'

services:
  db:
    image: postgres:16
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_crud
    ports:
      - "5432:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_net

volumes:
  postgres_data:

networks:
  fastapi_net:
    driver: bridge