version: '3.8'

services:
  db:
    image: registry.xetid.cu/proxy.mcr.microsoft.com/postgres:16
    container_name: server-postgres16
    restart: always
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: passwordtest
      POSTGRES_DB: test_db
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres16_network

volumes:
  postgres_data:

networks:
  postgres16_network:
    driver: bridge